server:
  port: 7070

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: akriti1209
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka # address where eureka server is running